'use strict';
const webglAvailable=(()=>{try{const canvas=document.createElement('canvas'),gl=canvas.getContext('webgl2')||canvas.getContext('webgl');if(!gl)return false;gl.getExtension('WEBGL_lose_context')?.loseContext();return true;}catch(_){return false;}})();
const data=window.TOP10,meta=window.VIEWER_META,$=id=>document.getElementById(id);
const esc=x=>String(x??'未提供').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>x===null||x===undefined||x===''?'未提供':typeof x==='number'?(Number.isFinite(x)?x.toFixed(3):'未提供'):String(x);
const clash=x=>x===true?'有':x===false?'无':'未提供';
const color=p=>p>=90?'#0053d6':p>=70?'#00b8d4':p>=50?'#f2cf30':'#e87722';
function af3Block(side,n,m){const row=(side==='two'?data.main:data[tab]).find(r=>String(r.design_index)===String(n.design_index)),context=data.af3_naming||window.AF3_NAMES.context({...data,namespace:'sr56_top10'},!!data.synthetic),name=window.AF3_NAMES.format(context,m.id,row?.rank);return '<p class="identity af3-name"><b>AF3 验证名称</b><br><code>'+esc(name)+'</code><br><small>设计项排名 · '+(side==='two'||tab==='main'?'原主阶段榜':'全循环最佳榜')+'；候选 ID 为当前模型</small><br><button data-af3-name="'+esc(name)+'">复制 AF3 名称</button></p>';}
document.addEventListener('click',e=>{const button=e.target.closest('[data-af3-name]');if(button)window.AF3_NAMES.copy(button);});
let tab='main',node,chosen,renderToken=0;const viewers=[null,null],scenes=[null,null],loading=new Map();
const modelById=new Map(data.nodes.flatMap(n=>n.models.map(m=>[m.id,{n,m}])));
$('identity').innerHTML='<p class="badge">'+esc(data.branch)+'</p><p><small>RUN '+esc(data.run_id)+'</small></p><p>'+esc(data.counts.actual_models)+(data.synthetic?' 个合成 RF3 模型</p>':' 个实际 RF3 模型</p>');
function extras(n,m){const s=m.summary||{},g=m.metrics||{};return [['pTM',s.ptm],['复杂物整体 pLDDT (0–100)',s.overall_plddt==null?null:s.overall_plddt*100],['整体 PAE Å',s.overall_pae],['链间 PAE Å',s.chain_pair_pae?.[0]?.[1]],['链间最小 PAE Å',s.chain_pair_pae_min?.[0]?.[1]],['self RMSD Å',g.binder_self_rmsd_A],['target RMSD Å',g.target_fragment_rmsd_A],['最小距离 Å',g.min_distance_A],['实际模型数',n.models.length],['完整 binder 序列',n.sequence]].map(([k,v])=>'<div><b>'+esc(k)+'</b> '+esc(fmt(v))+'</div>').join('');}
function rows(){const list=data[tab];$('main-tab').classList.toggle('active',tab==='main');$('best-tab').classList.toggle('active',tab==='best');const stem=tab==='main'?'main_top10':'refine_best_top10';$('csv').href=stem+'.csv';$('fasta').href=stem+'.fasta';$('ranking').innerHTML=list.map(r=>{const {n,m}=modelById.get(r.candidate_id),s=m.summary||{},g=m.metrics||{};return '<tr><td>'+esc(r.rank)+'</td><td><code>'+esc(m.id)+'</code></td><td>'+esc(m.round)+'</td><td>'+esc(fmt(s.ranking_score))+'</td><td>'+esc(fmt(meta.models[m.id].binder_ca_mean))+'</td><td>'+esc(fmt(s.iptm))+'</td><td>'+esc(fmt(g.binder_pose_rmsd_A))+'</td><td>'+esc(fmt(g.target_contact_residues))+'</td><td>'+clash(s.has_clash)+' / '+clash(g.has_geometric_clash)+'</td><td><button data-id="'+esc(m.id)+'">查看路径 ↗</button><details><summary>更多指标</summary><div class="extra">'+extras(n,m)+'</div></details></td></tr>';}).join('');$('ranking').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.id));if(node)draw();}
function load(n){if(window.TOP10_STRUCTURES?.[n.pair_id])return Promise.resolve(window.TOP10_STRUCTURES[n.pair_id]);if(loading.has(n.pair_id))return loading.get(n.pair_id);const promise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=n.script;s.onload=()=>resolve(window.TOP10_STRUCTURES[n.pair_id]);s.onerror=()=>{loading.delete(n.pair_id);reject(Error('structure script unavailable'));};document.head.appendChild(s);});loading.set(n.pair_id,promise);return promise;}
function panel(side,n,m,kind){const s=m.summary||{},g=m.metrics||{},mp=meta.models[m.id];const stage={rf3:'RF3预测',generated:'RFD3生成骨架',mpnn:'MPNN复合物'}[kind];const fields=[['ranking_score',s.ranking_score],['binder CA mean pLDDT (0–100)',mp.binder_ca_mean],['ipTM',s.iptm],['self RMSD Å',g.binder_self_rmsd_A],['pose RMSD Å',g.binder_pose_rmsd_A],['target RMSD Å',g.target_fragment_rmsd_A],['靶标接触残基数',g.target_contact_residues],['接触原子对数',g.contact_atom_pairs],['最小距离 Å',g.min_distance_A],['RF3 has_clash',clash(s.has_clash)],['几何碰撞',clash(g.has_geometric_clash)],['实际 RF3 模型数',n.models.length]];
$('meta-'+side).innerHTML=af3Block(side,n,m)+'<p class="identity">候选 '+esc(m.id)+'<br>阶段 '+stage+' · C'+esc(m.round)+' · 路径 '+esc(m.path??n.path??n.pair_id)+'<br>模型 M'+esc(m.model_index)+' · pair '+esc(n.pair_id)+'<br>结构 '+esc(kind==='rf3'?m.cif:n[kind])+'</p>'+(kind==='rf3'?'':'<p class="muted">参考指标来自 RF3 '+esc(m.id)+'；不代表此骨架的预测置信度。</p>')+'<p class="sequence">当前结构 binder 序列：'+esc(kind==='rf3'?n.sequence:meta.nodes[n.pair_id][kind].binder_sequence)+'</p><div class="metric-grid">'+fields.map(([k,v])=>'<div><b>'+esc(k)+'</b>'+esc(fmt(v))+'</div>').join('')+'</div><details><summary>补充指标、设计序列与来源</summary><div class="extra">'+extras(n,m)+'<p>目标序列 '+esc(data.target.sequence)+'</p><p>源包 '+esc(data.source_archive.filename)+'<br>源 SHA256 '+esc(data.source_archive.sha256)+'</p></div></details>';
const swatch=(c,t)=>'<span><i class="swatch" style="background:'+c+'"></i> '+t+'</span>';
$('legend-'+side).innerHTML=swatch('#a8b0ad','靶标')+(kind==='rf3'?[['#0053d6','≥90'],['#00b8d4','70–<90'],['#f2cf30','50–<70'],['#e87722','<50']].map(([c,t])=>swatch(c,'binder '+t)).join(''):swatch(kind==='generated'?'#c4a5eb':'#74d8b2','binder 固定颜色 · 无 pLDDT'));
$('downloads-'+side).innerHTML=[['当前结构 CIF',kind==='rf3'?m.cif:n[kind]],['RF3 CIF',m.cif],['confidence JSON',m.conf]].map(([label,path])=>'<a class="download" download href="'+esc(path)+'">'+label+' ↓</a>').join('');}
async function select(id){const found=modelById.get(id);if(!found)return;node=found.n;chosen=found.m;$('candidate').textContent=id;$('paths').innerHTML=data.nodes.filter(x=>x.design_index===node.design_index).map(x=>'<button data-id="'+esc(x.retained_model_ids[0])+'">'+(x.baseline?'C0 baseline':'C'+x.round+' '+esc(x.path??x.pair_id))+(x.selected?' ★':'')+'</button>').join('');$('paths').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.id));$('model').innerHTML=node.models.map(m=>'<option value="'+esc(m.id)+'" '+(m.id===id?'selected':'')+'>M'+esc(m.model_index)+' · '+esc(fmt(m.summary?.ranking_score))+'</option>').join('');await draw();}
function styleScene(i){const v=viewers[i],sc=scenes[i];if(!v||!sc)return;const side=i?'two':'one',mp=sc.mapping;v.setStyle({},{cartoon:{hidden:true}});if($('target-'+side).checked)v.setStyle({chain:mp.target},{cartoon:{color:'#a8b0ad'}});if($('binder-'+side).checked)v.setStyle({chain:mp.binder},{cartoon:{colorfunc:a=>sc.kind==='rf3'?color(mp.ca_plddt[String(a.resi)]):sc.kind==='generated'?'#c4a5eb':'#74d8b2'}});v.render();}
async function draw(){if(!node)return;const token=++renderToken,n=node,m=chosen,kind=$('kind').value;const baseline=modelById.get(meta.baselines[String(n.design_index)]);panel('one',n,m,kind);panel('two',baseline.n,baseline.m,'rf3');try{const [current,base]=await Promise.all([load(n),load(baseline.n)]);if(token!==renderToken)return;const text=[kind==='rf3'?current.models.find(x=>x.id===m.id).cif:current[kind],base.models.find(x=>x.id===baseline.m.id).cif];for(let i=0;i<2;i++){const side=i?'two':'one';try{if(!webglAvailable)throw Error('WebGL unavailable');let v=viewers[i];if(!v){$('view-'+side).replaceChildren();v=$3Dmol.createViewer($('view-'+side),{backgroundColor:'#172b28'});viewers[i]=v;}v.clear();v.addModel(text[i],'cif');scenes[i]={kind:i?'rf3':kind,mapping:i?meta.models[baseline.m.id]:kind==='rf3'?meta.models[m.id]:meta.nodes[n.pair_id][kind]};styleScene(i);v.zoomTo();v.render();scenes[i].initialView=v.getView();}catch(error){if(viewers[i])viewers[i].clear();viewers[i]=null;scenes[i]=null;$('view-'+side).innerHTML='<p class="empty">WebGL结构显示不可用。上方身份与指标可继续阅读，下方可下载原始 CIF。</p>';}}}catch(error){if(token!==renderToken)return;['one','two'].forEach(side=>$('view-'+side).innerHTML='<p class="empty">结构资源未能读取。请下载 CIF；指标与排名仍可阅读。</p>');}}
$('main-tab').onclick=()=>{tab='main';rows();};$('best-tab').onclick=()=>{tab='best';rows();};$('model').onchange=()=>select($('model').value);$('kind').onchange=draw;['one','two'].forEach((side,i)=>{['target','binder'].forEach(role=>$(`${role}-${side}`).onchange=()=>styleScene(i));$('reset-'+side).onclick=()=>{if(viewers[i]){viewers[i].setView(scenes[i].initialView);viewers[i].render();}};});window.addEventListener('resize',()=>viewers.forEach(v=>{if(v){v.resize();v.render();}}));rows();select(data.main[0].candidate_id);
